@password=123456

###
GET {{host}}/api/greeting HTTP/1.1

###
GET {{host}}/api/greeting HTTP/1.1
Authorization: Basic user {{password}}

###
POST {{host}}/api/greeting?name=Kenny HTTP/1.1
Authorization: Basic user {{password}}
Content-Type: application/json

{
    "gender": "M",
    "idNo": "123456"
}

###
PUT {{host}}/api/greeting/Kenny HTTP/1.1
Authorization: Basic user {{password}}

###

POST {{host}}/authorize/login
Content-Type: application/json

{
  "username" : "user",
  "password" : "123456"
}

###

POST {{host}}/authorize/register
Accept-Language: zh-CN
Content-Type: application/json

{
  "name": "张三李四",
  "username": "PeterWong",
  "password": "P@ssw0rd!1",
  "matchingPassword": "P@ssw0rd!1",
  "email": "zs@local.com"
}

###
GET {{host}}/api/principal HTTP/1.1
Authorization: Basic user {{password}}

###
GET {{host}}/api/authentication HTTP/1.1
Authorization: Basic user {{password}}