@password=060dc5bc-a2cd-4fa1-9895-dd3057c2e8e4

###
GET http://localhost:8080/api/greeting HTTP/1.1
Authorization: Basic user {{password}}

###
POST http://localhost:8080/api/greeting?name=Kenny HTTP/1.1
Authorization: Basic user {{password}}
Content-Type: application/json

{
    "gender": "M",
    "idNo": "123456"
}

###
PUT http://localhost:8080/api/greeting/Kenny HTTP/1.1
Authorization: Basic user {{password}}

###