logging:
  pattern:
    console: '%clr(%d{E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint}
              %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n'
server:
  error:
    whitelabel:
      enabled: true
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: uaa
  messages:
    basename: messages
    encoding: UTF-8
    always-use-message-format: true
    use-code-as-default-message: false
  datasource:
    initialization-mode: embedded
  mail:
    host: ${SMTP_HOST}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${SMTP_USERNAME}
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}

kenny:
  jwt:
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000
  sms-provider:
    name: ali
  email-provider:
    api-key: ${EMAIL_API_KEY}
    name: api
